// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:20fda4df-2bf7-4729-a6ac-d7ff1de44219",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_CDG61BA3h",
    "aws_user_pools_web_client_id": "6tuljpomeqageinjbp28dcihh9",
    "aws_appsync_graphqlEndpoint": "https://i3zjkdglvrfrnkc6esq6gig54m.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
